### ISSUE TITLE
Add email+password in account who sign up using phone number + otp

### ISSUE THREAD

**Issue by heru-wijaya** [supertokens/supertokens-golang#424] opened 2024-08-06 03:02 UTC
how we can achieve this in supertoken ? 
- user signup using phone number + password, when this user add his email + password, he can sign in using email + password or SSO as well
- user signup using email + password can sign in using SSO as well..when this user want to add his phone number, he can sign in using phone number + otp

Thank you

**Comment by rishabhpoddar** [comment] 2024-08-06 05:16
Hey. This requires account linking to be enabled, and we don't yet support that in our golang SDK (as of this writing). If you instead switch to using our node sdk, then you can use account linking to achieve this flow fairly easily.

Also, since this is not a bug in the sdk, im closing this issue (but feel free to keep posting in here without reopening it).

Thanks

**Closed by rishabhpoddar** 2024-08-06 05:16 UTC

**Comment by heru-wijaya** [comment] 2024-08-06 07:06
hey thanks for answering..allright its okay, I will not reopen it @rishabhpoddar 

is there any suggestion to achieve this with golang? because my system currently use golang..

**Comment by rishabhpoddar** [comment] 2024-08-06 07:08
Well, you will have to manually do account linking using your own logic, and that is non trivial to explain here. Sorry, can't be of much help since the answer is not straightforward at all.
